const MongoClient = require("mongodb").MongoClient;
const express = require("express");
const { request } = require("express");
const app = express();
app.use(express.static(__dirname + "/public"));
var email;
var password;
var firstUser;
const nodemailer = require("nodemailer");
//Email Address: ut9614529@gmail.com(user1)
//Password:!Q@W3e4r
//Email Address: ut6360@gmail.com(user2)
//Password:!Q@W3e4r

app.get("/save_userdetails", function (req, res) {
  insertdata_userdetails({
    firstName: req.query.firstName,
    lastName: req.query.lastName,
    signupEmail: req.query.signupEmail,
    signupPassword: req.query.signupPassword,
    profilePhoto: `${"./images/" + req.query.firstName}.jpg`,
  });
});

app.get("/check_user", function (req, res) {
  email = req.query.email;
  password = req.query.password;

  collection_userdetails
    .findOne({ signupEmail: email, signupPassword: password })
    .then((userDetails) => {
      try {
        if (
          userDetails.signupEmail === email &&
          userDetails.signupPassword === password
        ) {
          res.send(userDetails);
        } else {
          res.send("./index.html");
        }
      } catch (error) {
        console.log("error caught");
        res.send("./index.html");
      }
    });
});

app.get("/insert_userLikes", function (req, res) {
  usersLikes = req.query.usersLikes;
  console.log("I am here");
  insertdata_userslikes({
    usersLikes,
  });
});

app.get("/check_userlikes", function (req, res) {
  collection_usersLikes.findOne({}, { usersLikes: 1 }).then((users) => {
    if (users == null) {
      res.send("null");
    } else {
      console.log(users.usersLikes[6].count);
      res.send(users);
    }
  });
});

app.get("/delete_userlikes", function (req, res) {
  collection_usersLikes.remove({}, { usersLikes: 1 });
});

app.get("/userdetails", function (req, res) {
  collection_userdetails
    .findOne({ signupEmail: email, signupPassword: password })
    .then((userDetails) => {
      res.send(userDetails);
    });
});

app.get("/sendEmail", function (req, res) {
  var whoLikesWho = req.query.whoLikesWho;
  var email_1 = "ut9614529@gmail.com"; //user1
  var email_2 = "ut63620@gmail.com"; //user2

  var transport = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    secure: false,
    auth: {
      user: email_1, //example of generated by Mailtrap
      pass: "!Q@W3e4r", //example of generated by Mailtrap
    },
  });

  var mailOptions = {
    from: email_1,
    to: email_2,
    subject: "Tinder Clone App",
    text: "Hey there, " + whoLikesWho,
  };

  transport.sendMail(mailOptions, (error, info) => {
    if (error) {
      return console.log(error);
    }
    console.log("Email sent: " + info.response);
    setTimeout(function () {
      var transport = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port: 587,
        secure: false,
        auth: {
          user: email_2, //example of generated by Mailtrap
          pass: "!Q@W3e4r", //example of generated by Mailtrap
        },
      });

      var mailOptions = {
        from: email_2,
        to: email_1,
        subject: "Tinder Clone App",
        text: "Hey there, " + whoLikesWho,
      };

      transport.sendMail(mailOptions, (error, info) => {
        if (error) {
          return console.log(error);
        }
        console.log("Email sent: " + info.response);
      });
    }, 2000);
  });
});

app.listen(3000);
console.log("Server running at Port: 3000");

//DATABASE MONGODB
const uri =
  "mongodb+srv://Hassan:SIT725@sit725.bketa.mongodb.net/SIT725?retryWrites=true&w=majority";
const client = new MongoClient(uri, {
  useNewUrlParser: true,
  seUnifiedTopology: true,
});

let collection_userdetails;
let collection_usersLikes;

const insertdata_userdetails = ({
  firstName,
  lastName,
  signupEmail,
  signupPassword,
  profilePhoto,
}) => {
  collection_userdetails.insertOne({
    firstName,
    lastName,
    signupEmail,
    signupPassword,
    profilePhoto,
  });
};

const insertdata_userslikes = ({ usersLikes }) => {
  collection_usersLikes.insertOne({
    usersLikes,
  });
};

client.connect((err) => {
  collection_userdetails = client.db("SIT725").collection("userdetails");
  collection_usersLikes = client.db("SIT725").collection("usersLikes");
});
